# Generated by Django 5.0.3 on 2024-03-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('release_date', models.DateField(max_length=10)),
                ('lte_exists', models.BooleanField(default=True)),
                ('slug', models.SlugField(max_length=100)),
            ],
        ),
    ]
