# Generated by Django 5.0.3 on 2024-04-15 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('group',), 'verbose_name': 'Ученик', 'verbose_name_plural': 'Ученики'},
        ),
    ]
